// Code generated by MockGen. DO NOT EDIT.
// Source: ./requester/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./requester/interfaces.go -destination=./mocks/requester_mock.go -package=mocks
//

// Package mock is a generated GoMock package.
package mocks

import (
	"github.com/midedickson/github-service/dto"
	"github.com/stretchr/testify/mock"
)

// MockRequester is a mock of Requester interface.
type MockRequester struct {
	mock.Mock
}




// GetAllUserRepositories mocks base method.
func (m *MockRequester) GetAllUserRepositories(owner string) (*[]dto.RepositoryInfoResponseDTO, error) {
	args := m.Called(owner)
	return args.Get(0).(*[]dto.RepositoryInfoResponseDTO), args.Error(1)
}



// GetRepositoryCommits mocks base method.
func (m *MockRequester) GetRepositoryCommits(owner, repo string) (*[]dto.CommitResponseDTO, error) {
	args := m.Called(owner, repo)
	return args.Get(0).(*[]dto.CommitResponseDTO), args.Error(1)
}


// GetRepositoryInfo mocks base method.
func (m *MockRequester) GetRepositoryInfo(owner, repo string) (*dto.RepositoryInfoResponseDTO, error) {
	args := m.Called(owner, repo)
	return args.Get(0).(*dto.RepositoryInfoResponseDTO), args.Error(1)
}